name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      # Nouvelle étape : Installation de Node.js et Expo CLI
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Assurez-vous que cette version est compatible avec votre projet

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install Dependencies
        run: npm install

      # Nouvelle étape : Export Expo pour le Web
      - name: Export Expo for Web
        run: npx expo export --platform web

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_OCEAN_0EEE1D103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Chemin du code source de l'application
          api_location: "" # Chemin du code source de l'API - optionnel
          output_location: "dist" # Dossier de contenu généré par expo export:web

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_OCEAN_0EEE1D103 }}
          action: "close"
